### ISSUE TITLE
Dies with an empty post body

### ISSUE THREAD

**Issue by combs** [fusioneng/speed-bumps#89]
With WP_DEBUG enabled, empty posts output:

`Notice: Undefined variable: index in /home/washingtonian/wp-code/releases/324/html/wp-content/plugins/speed-bumps/speed-bumps.php on line 197`

It looks like these lines are related:

```
		$parts = Text::split_paragraphs( $the_content );
		$total_paragraphs = count( $parts );
		foreach ( $parts as $index => $part ) {
```

What's a good desired behavior? I think that last-ditch inserts could still be inserted in this case...

**Comment by goldenapples** [comment]
Makes sense. In that case, all that would be necessary would be to set $index to 0 before that foreach loop, so that even if there's no post content, the index isn't undefined in the later constraint check. I'd never noticed that error because I'd always set a minimum content length constraint when I've used the plugin.

Care to open a PR that enables this?

**Comment by combs** [comment]
Ha, yep, that did the trick. Here you go. Thanks!
https://github.com/fusioneng/speed-bumps/pull/90
